### ISSUE TITLE
Refine ILA Sim

### ISSUE THREAD

**Issue by Bo-Yuan-Huang** [Bo-Yuan-Huang/ILAng#107]
- rename the directory
- update to convention
- double check warnings

**Comment by Bo-Yuan-Huang** [comment]
let's rename the directory to 'target-sc'

**Comment by yuex1994** [comment]
Just saw you push the changes to the dir name.
I'll convert the other names (class, function, var etc.) similarly as the directory name, does this sound good?

**Comment by Bo-Yuan-Huang** [comment]
Class and function names may be fine for now concerning the effort to change them. But comment/annotation definitely needs to be added, especially for public functions/member data.
